# basic config
[basic]
# timeout for http request
timeout = "30s"
listen = "0.0.0.0:3000"
processing_limit = 1_000

[opendal]
url = "file://~/Downloads"

[optim]
quality = 80
speed = 3
max_age = "1440h"
auto_output_types = ["avif", "png"]
